const arcaneComments: string[] = [
        "Le Fou représente l'innocence, la spontanéité et les nouveaux départs, symbolisant souvent un voyage imprévisible rempli de possibilités infinies.",
        "C'est une carte qui symbolise de nouveaux départs, de la créativité et de l'enthousiasme.",
        "La Papesse symbolise la sagesse, l'intuition et la connaissance intérieure.",
        "C'est une carte qui incarne la croissance, l'abondance et la connexion avec la nature, ainsi que l'expression de soi à travers des moyens créatifs.",
        "L'Empereur représente l'ordre, la structure et l'autorité, incarnant la stabilité et le leadership et le contrôle rationnel.",
        "Le Pape symbolise la tradition, la spiritualité et les enseignements religieux, représentant la sagesse collective, la transmission du savoir et les valeurs morales.",
        "C'est une carte qui incarne l'amour, l'union et l'équilibre dans les relations, ainsi que la prise de décisions importantes concernant le cœur et les relations personnelles.",
        "C'est une carte qui représente la maîtrise de soi, la confiance en soi et la capacité à surmonter les obstacles grâce à la volonté et à la discipline.",
        "La Justice symbolise l'équité, la vérité et la responsabilité, représentant l'importance de prendre des décisions justes et équilibrées basées sur des principes moraux et éthiques.",
        "C'est une carte qui incarne la recherche de la vérité intérieure, la contemplation et la poursuite de sagesse à travers l'introspection et la solitude.",
        "C'est une carte qui représente les hauts et les bas de la vie, les cycles de changement et l'inévitabilité du destin, soulignant l'importance de s'adapter aux fluctuations de la vie.",
        "La Force symbolise le courage, la maîtrise de soi et la résilience, représentant la capacité à surmonter les défis avec compassion, patience et détermination intérieure.",
        "C'est une carte qui incarne la nécessité de lâcher prise, de voir les choses sous un angle différent et de faire des sacrifices pour la croissance personnelle et spirituelle.",
        "L'arcane XIII représente la transformation, le changement et la renaissance, symbolisant la fin d'un cycle et le début d'un nouveau chapitre dans la vie.",
        "La Tempérance symbolise l'équilibre, la modération et l'harmonie, représentant la capacité à trouver un terrain d'entente, à intégrer des opposés et à maintenir la paix intérieure à travers la patience et la compréhension.",
        "Le Diable symbolise l'attachement, la tentation et les aspects sombres de la nature humaine, représentant souvent les dépendances, les peurs et les illusions qui entravent la liberté personnelle.",
        "La Tour symbolise la destruction soudaine, le bouleversement et la révélation, représentant souvent des changements inattendus qui ébranlent les fondations établies et conduisent à une transformation profonde.",
        "C'est une carte qui incarne la foi en l'avenir, la clarté mentale et la connexion spirituelle, offrant un sentiment de paix et de renouveau après des périodes de difficulté.",
        "La Lune symbolise l'intuition, les émotions et les aspects cachés de la psyché, représentant souvent l'incertitude, les illusions et les peurs subconscientes qui peuvent obscurcir la perception de la réalité.",
        "C'est une carte qui incarne l'optimisme, la clarté et l'énergie positive, symbolisant la réussite, la croissance personnelle et le bonheur dans la vie.",
        "Le Jugement symbolise la renaissance, l'éveil et la prise de conscience, représentant souvent un moment de vérité où l'on évalue ses actions passées et prend des décisions importantes pour l'avenir.",
        "C'est une carte qui incarne la réalisation, l'harmonie et l'unité, symbolisant la fin d'un cycle important et le début d'une nouvelle phase de croissance et d'expansion dans la vie.",
];
export default arcaneComments;
